// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacePark;

namespace SpaceApp.Migrations
{
    [DbContext(typeof(SpaceParkContext))]
    [Migration("20210329172051_SpaceApp")]
    partial class SpaceApp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("SpacePark.ParkEvent", b =>
                {
                    b.Property<int>("ParkEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StarShipId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeParked")
                        .HasColumnType("TEXT");

                    b.HasKey("ParkEventId");

                    b.HasIndex("PersonId");

                    b.HasIndex("StarShipId");

                    b.ToTable("ParkEvent");
                });

            modelBuilder.Entity("SpacePark.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("SpacePark.StarShip", b =>
                {
                    b.Property<int>("StarShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StarShipName")
                        .HasColumnType("TEXT");

                    b.HasKey("StarShipId");

                    b.ToTable("StarShip");
                });

            modelBuilder.Entity("SpacePark.ParkEvent", b =>
                {
                    b.HasOne("SpacePark.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpacePark.StarShip", "StarShip")
                        .WithMany()
                        .HasForeignKey("StarShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("StarShip");
                });
#pragma warning restore 612, 618
        }
    }
}
